# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import holoholo_shared_pb2 as holoholo__shared__pb2

from holoholo_shared_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='Holoholo.Rpc',
  syntax='proto3',
  serialized_pb=_b('\n\trpc.proto\x12\x0cHoloholo.Rpc\x1a\x15holoholo_shared.proto\"A\n\rMapFieldEntry\x12!\n\x03key\x18\x01 \x01(\x0e\x32\x14.Holoholo.Rpc.Method\x12\r\n\x05value\x18\x02 \x01(\x0c\"E\n\nAuthTicket\x12\r\n\x05start\x18\x01 \x01(\x0c\x12\x1b\n\x13\x65xpire_timestamp_ms\x18\x02 \x01(\x04\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x0c\"\xca\x03\n\x17RpcRequestEnvelopeProto\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x04\x12\x12\n\nrequest_id\x18\x03 \x01(\x04\x12.\n\tparameter\x18\x04 \x03(\x0b\x32\x1b.Holoholo.Rpc.MapFieldEntry\x12\x0e\n\x06\x66ooter\x18\x06 \x01(\x0c\x12\x0b\n\x03lat\x18\x07 \x01(\x01\x12\x0c\n\x04long\x18\x08 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\t \x01(\x01\x12<\n\x04\x61uth\x18\n \x01(\x0b\x32..Holoholo.Rpc.RpcRequestEnvelopeProto.AuthInfo\x12-\n\x0b\x61uth_ticket\x18\x0b \x01(\x0b\x32\x18.Holoholo.Rpc.AuthTicket\x12\x18\n\x10protocol_version\x18\x0c \x01(\x03\x1a\x91\x01\n\x08\x41uthInfo\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x41\n\x05token\x18\x02 \x01(\x0b\x32\x32.Holoholo.Rpc.RpcRequestEnvelopeProto.AuthInfo.JWT\x1a\x30\n\x03JWT\x12\x10\n\x08\x63ontents\x18\x01 \x01(\t\x12\x17\n\x0f\x63ontents_length\x18\x02 \x01(\x05\"\x85\x01\n\x18RpcResponseEnvelopeProto\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x04\x12\x13\n\x0bresponse_id\x18\x02 \x01(\x04\x12\x0f\n\x07\x61pi_url\x18\x03 \x01(\t\x12\x0e\n\x06\x66ooter\x18\x06 \x01(\x0c\x12\x0f\n\x07returns\x18\x64 \x03(\x0c\x12\r\n\x05\x65rror\x18\x65 \x01(\tP\x00\x62\x06proto3')
  ,
  dependencies=[holoholo__shared__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MAPFIELDENTRY = _descriptor.Descriptor(
  name='MapFieldEntry',
  full_name='Holoholo.Rpc.MapFieldEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Holoholo.Rpc.MapFieldEntry.key', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Holoholo.Rpc.MapFieldEntry.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=115,
)


_AUTHTICKET = _descriptor.Descriptor(
  name='AuthTicket',
  full_name='Holoholo.Rpc.AuthTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='Holoholo.Rpc.AuthTicket.start', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expire_timestamp_ms', full_name='Holoholo.Rpc.AuthTicket.expire_timestamp_ms', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='Holoholo.Rpc.AuthTicket.end', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=186,
)


_RPCREQUESTENVELOPEPROTO_AUTHINFO_JWT = _descriptor.Descriptor(
  name='JWT',
  full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.AuthInfo.JWT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contents', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.AuthInfo.JWT.contents', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contents_length', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.AuthInfo.JWT.contents_length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=647,
)

_RPCREQUESTENVELOPEPROTO_AUTHINFO = _descriptor.Descriptor(
  name='AuthInfo',
  full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.AuthInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='provider', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.AuthInfo.provider', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.AuthInfo.token', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RPCREQUESTENVELOPEPROTO_AUTHINFO_JWT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=647,
)

_RPCREQUESTENVELOPEPROTO = _descriptor.Descriptor(
  name='RpcRequestEnvelopeProto',
  full_name='Holoholo.Rpc.RpcRequestEnvelopeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.status_code', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.request_id', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameter', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.parameter', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='footer', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.footer', index=3,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.lat', index=4,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='long', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.long', index=5,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.altitude', index=6,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.auth', index=7,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth_ticket', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.auth_ticket', index=8,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protocol_version', full_name='Holoholo.Rpc.RpcRequestEnvelopeProto.protocol_version', index=9,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RPCREQUESTENVELOPEPROTO_AUTHINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=647,
)


_RPCRESPONSEENVELOPEPROTO = _descriptor.Descriptor(
  name='RpcResponseEnvelopeProto',
  full_name='Holoholo.Rpc.RpcResponseEnvelopeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='Holoholo.Rpc.RpcResponseEnvelopeProto.status_code', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response_id', full_name='Holoholo.Rpc.RpcResponseEnvelopeProto.response_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='api_url', full_name='Holoholo.Rpc.RpcResponseEnvelopeProto.api_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='footer', full_name='Holoholo.Rpc.RpcResponseEnvelopeProto.footer', index=3,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='returns', full_name='Holoholo.Rpc.RpcResponseEnvelopeProto.returns', index=4,
      number=100, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='Holoholo.Rpc.RpcResponseEnvelopeProto.error', index=5,
      number=101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=650,
  serialized_end=783,
)

_MAPFIELDENTRY.fields_by_name['key'].enum_type = holoholo__shared__pb2._METHOD
_RPCREQUESTENVELOPEPROTO_AUTHINFO_JWT.containing_type = _RPCREQUESTENVELOPEPROTO_AUTHINFO
_RPCREQUESTENVELOPEPROTO_AUTHINFO.fields_by_name['token'].message_type = _RPCREQUESTENVELOPEPROTO_AUTHINFO_JWT
_RPCREQUESTENVELOPEPROTO_AUTHINFO.containing_type = _RPCREQUESTENVELOPEPROTO
_RPCREQUESTENVELOPEPROTO.fields_by_name['parameter'].message_type = _MAPFIELDENTRY
_RPCREQUESTENVELOPEPROTO.fields_by_name['auth'].message_type = _RPCREQUESTENVELOPEPROTO_AUTHINFO
_RPCREQUESTENVELOPEPROTO.fields_by_name['auth_ticket'].message_type = _AUTHTICKET
DESCRIPTOR.message_types_by_name['MapFieldEntry'] = _MAPFIELDENTRY
DESCRIPTOR.message_types_by_name['AuthTicket'] = _AUTHTICKET
DESCRIPTOR.message_types_by_name['RpcRequestEnvelopeProto'] = _RPCREQUESTENVELOPEPROTO
DESCRIPTOR.message_types_by_name['RpcResponseEnvelopeProto'] = _RPCRESPONSEENVELOPEPROTO

MapFieldEntry = _reflection.GeneratedProtocolMessageType('MapFieldEntry', (_message.Message,), dict(
  DESCRIPTOR = _MAPFIELDENTRY,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.MapFieldEntry)
  ))
_sym_db.RegisterMessage(MapFieldEntry)

AuthTicket = _reflection.GeneratedProtocolMessageType('AuthTicket', (_message.Message,), dict(
  DESCRIPTOR = _AUTHTICKET,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.AuthTicket)
  ))
_sym_db.RegisterMessage(AuthTicket)

RpcRequestEnvelopeProto = _reflection.GeneratedProtocolMessageType('RpcRequestEnvelopeProto', (_message.Message,), dict(

  AuthInfo = _reflection.GeneratedProtocolMessageType('AuthInfo', (_message.Message,), dict(

    JWT = _reflection.GeneratedProtocolMessageType('JWT', (_message.Message,), dict(
      DESCRIPTOR = _RPCREQUESTENVELOPEPROTO_AUTHINFO_JWT,
      __module__ = 'rpc_pb2'
      # @@protoc_insertion_point(class_scope:Holoholo.Rpc.RpcRequestEnvelopeProto.AuthInfo.JWT)
      ))
    ,
    DESCRIPTOR = _RPCREQUESTENVELOPEPROTO_AUTHINFO,
    __module__ = 'rpc_pb2'
    # @@protoc_insertion_point(class_scope:Holoholo.Rpc.RpcRequestEnvelopeProto.AuthInfo)
    ))
  ,
  DESCRIPTOR = _RPCREQUESTENVELOPEPROTO,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.RpcRequestEnvelopeProto)
  ))
_sym_db.RegisterMessage(RpcRequestEnvelopeProto)
_sym_db.RegisterMessage(RpcRequestEnvelopeProto.AuthInfo)
_sym_db.RegisterMessage(RpcRequestEnvelopeProto.AuthInfo.JWT)

RpcResponseEnvelopeProto = _reflection.GeneratedProtocolMessageType('RpcResponseEnvelopeProto', (_message.Message,), dict(
  DESCRIPTOR = _RPCRESPONSEENVELOPEPROTO,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.RpcResponseEnvelopeProto)
  ))
_sym_db.RegisterMessage(RpcResponseEnvelopeProto)


# @@protoc_insertion_point(module_scope)
